<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <RootNamespace>Fellowship_overlay</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

 <PropertyGroup>
  <Version>1.0.4</Version>                <!-- use this for NetSparkle sparkle:version -->
  <AssemblyVersion>1.0.4.0</AssemblyVersion>
  <FileVersion>1.0.4.0</FileVersion>
  <InformationalVersion>1.0.4</InformationalVersion>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetSparkleUpdater.UI.WPF" Version="3.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\FellowshipBuffs.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\BuffImages\spirited_vortex.png" />
    <Resource Include="Assets\BuffImages\spirited_strikes.png" />
    <Resource Include="Assets\BuffImages\warden_of_the_temple.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
